### ISSUE TITLE
Needs more Ferris.

### ISSUE THREAD

**Issue by LePichu** [FedericoSchonborn/discord-emoji#1]
Eyo turtle-man, can we hab more Fewwis? 🦀

**Comment by fdschonborn** [comment]
`:ferrisRealization:`

![ferrisRealization512](https://user-images.githubusercontent.com/62166915/155074059-40da3030-bfcb-42f7-af5d-7b9815a4e0c2.png)

**Comment by fdschonborn** [comment]
`:ferrisChefKiss:`

![ferrisChefKiss512](https://user-images.githubusercontent.com/62166915/155074131-7161c2d8-093f-457c-93e9-5a650d5783a5.png)

**Comment by fdschonborn** [comment]
I forgor the rest I had to make :skull:

**Comment by FedericoSchonborn** [comment]
I added a lot more Ferris ![ferrisUwU](https://user-images.githubusercontent.com/62166915/180581531-6f6aec2f-a2d8-41b0-86b7-d36a64d8391b.png)
